/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIssueRouteImport } from './routes/api/issue'
import { Route as ApiLogsRouteImport } from './routes/api/logs'
import { Route as ApiPictureRouteImport } from './routes/api/picture'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiTicketRouteImport } from './routes/api/ticket'
import { Route as PProjectRouteImport } from './routes/p.$project'
import { Route as ApiLogsProjectRouteImport } from './routes/api/logs.$project'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIssueRoute = ApiIssueRouteImport.update({
  id: '/api/issue',
  path: '/api/issue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api/logs',
  path: '/api/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPictureRoute = ApiPictureRouteImport.update({
  id: '/api/picture',
  path: '/api/picture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketRoute = ApiTicketRouteImport.update({
  id: '/api/ticket',
  path: '/api/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectRoute = PProjectRouteImport.update({
  id: '/p/$project',
  path: '/p/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogsProjectRoute = ApiLogsProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => ApiLogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/issue': typeof ApiIssueRoute
  '/api/logs': typeof ApiLogsRouteWithChildren
  '/api/picture': typeof ApiPictureRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/ticket': typeof ApiTicketRoute
  '/p/$project': typeof PProjectRoute
  '/api/logs/$project': typeof ApiLogsProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/issue': typeof ApiIssueRoute
  '/api/logs': typeof ApiLogsRouteWithChildren
  '/api/picture': typeof ApiPictureRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/ticket': typeof ApiTicketRoute
  '/p/$project': typeof PProjectRoute
  '/api/logs/$project': typeof ApiLogsProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/issue': typeof ApiIssueRoute
  '/api/logs': typeof ApiLogsRouteWithChildren
  '/api/picture': typeof ApiPictureRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/ticket': typeof ApiTicketRoute
  '/p/$project': typeof PProjectRoute
  '/api/logs/$project': typeof ApiLogsProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/issue'
    | '/api/logs'
    | '/api/picture'
    | '/api/projects'
    | '/api/ticket'
    | '/p/$project'
    | '/api/logs/$project'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/issue'
    | '/api/logs'
    | '/api/picture'
    | '/api/projects'
    | '/api/ticket'
    | '/p/$project'
    | '/api/logs/$project'
  id:
    | '__root__'
    | '/'
    | '/api/issue'
    | '/api/logs'
    | '/api/picture'
    | '/api/projects'
    | '/api/ticket'
    | '/p/$project'
    | '/api/logs/$project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiIssueRoute: typeof ApiIssueRoute
  ApiLogsRoute: typeof ApiLogsRouteWithChildren
  ApiPictureRoute: typeof ApiPictureRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiTicketRoute: typeof ApiTicketRoute
  PProjectRoute: typeof PProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/issue': {
      id: '/api/issue'
      path: '/api/issue'
      fullPath: '/api/issue'
      preLoaderRoute: typeof ApiIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logs': {
      id: '/api/logs'
      path: '/api/logs'
      fullPath: '/api/logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/picture': {
      id: '/api/picture'
      path: '/api/picture'
      fullPath: '/api/picture'
      preLoaderRoute: typeof ApiPictureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ticket': {
      id: '/api/ticket'
      path: '/api/ticket'
      fullPath: '/api/ticket'
      preLoaderRoute: typeof ApiTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project': {
      id: '/p/$project'
      path: '/p/$project'
      fullPath: '/p/$project'
      preLoaderRoute: typeof PProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logs/$project': {
      id: '/api/logs/$project'
      path: '/$project'
      fullPath: '/api/logs/$project'
      preLoaderRoute: typeof ApiLogsProjectRouteImport
      parentRoute: typeof ApiLogsRoute
    }
  }
}

interface ApiLogsRouteChildren {
  ApiLogsProjectRoute: typeof ApiLogsProjectRoute
}

const ApiLogsRouteChildren: ApiLogsRouteChildren = {
  ApiLogsProjectRoute: ApiLogsProjectRoute,
}

const ApiLogsRouteWithChildren =
  ApiLogsRoute._addFileChildren(ApiLogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiIssueRoute: ApiIssueRoute,
  ApiLogsRoute: ApiLogsRouteWithChildren,
  ApiPictureRoute: ApiPictureRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiTicketRoute: ApiTicketRoute,
  PProjectRoute: PProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
